#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @author	 Ilya Kogan <ikogan@flarecode.com>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
# @copyright Copyright (c) 2015		 Ilya Kogan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_KRB5_CONFIG="/etc/krb5.conf"
OMV_KRB5_KEYTAB="/etc/krb5.keytab"

rm ${OMV_KRB5_CONFIG}

[ "$(omv_config_get "//services/kerberos/enable")" = "0"] && exit 0

if [ "$(omv_config_get "//services/kerberos/logging")" = "1" ]; then
	xmlstarlet sel -t -m "//services/kerberos" \
		-o "[logging]" -n \
		-o "	" -o "default = FILE:/var/log/kerberos.log" -n \
	-b \
	${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_KRB5_CONFIG}
fi

xmlstarlet sel -t -m "//services/kerberos" \
	-o "[libdefaults]" -n \
	-o "	" -v "concat('default_realm = ', realm)" -n \
	-n \
	-o "[realms]" -n \
	-o "	" -v "concat(realm, ' = {')" -n \
	-o "		" -v "concat('kdc = ', kdc)" -n \
	-o "		" -v "concat('admin_server = ', adminServer)" -n \
	-o "		" -v "concat('default_domain = ', realm)" -n \
	-o "	}" -n \
	-n \
	-o "[domain_realm]" -n \
	-o "	" -v "translate(realm, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')" -v "concat(' = ', realm)" -n \
-b \
${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_KRB5_CONFIG}

# Run these manually for now since SSH and NFS don't support running
# things like this.
${OMV_MKCONF_SCRIPTS_DIR}/nfs.d/kerberos
${OMV_MKCONF_SCRIPTS_DIR}/ssh.d/kerberos