#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="kerberos"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            # Create default configuration
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "realm" ""
            omv_config_add_element "${SERVICE_XPATH}" "kdc" ""
            omv_config_add_element "${SERVICE_XPATH}" "adminServer" ""

            omv_config_add_element "${SERVICE_XPATH}" "smb-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "pam-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "nfs-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "ssh-enabled"   "1"

            omv_config_add_element "${SERVICE_XPATH}" "logging" "0"
        else
            # Migrate existing configuration
            if omv_config_exists "${SERVICE_XPATH}/kdc"; then
                # Need to move the singular KDC element to multiple KDCs
                KDC=$(omv_config_get "${SERVICE_XPATH}/kdc")
                omv_config_add_element "${SERVICE_XPATH}" "kdcs"
                omv_config_add_element "${SERVICE_XPATH}/kdcs" "kdc" "${KDC}"
                omv_config_delete "${SERVICE_XPATH}/kdc"
            fi
        fi

	    omv-mkconf kerberos
        omv-mkconf nfsd
        omv-mkconf pam
        omv-mkconf samba
        omv-mkconf ssh

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
        
        invoke-rc.d nfs-kernel-server restart || true
        invoke-rc.d smbd restart || true
        invoke-rc.d ssh restart || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
