#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="kerberos"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "realm" ""
            omv_config_add_element "${SERVICE_XPATH}" "kdc" ""
            omv_config_add_element "${SERVICE_XPATH}" "adminServer" ""

            omv_config_add_element "${SERVICE_XPATH}" "smb-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "pam-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "nfs-enabled"   "1"
            omv_config_add_element "${SERVICE_XPATH}" "ssh-enabled"   "1"

            omv_config_add_element "${SERVICE_XPATH}" "logging" "0"
        fi

        # Since libpam-krb5 automatically enables itself on install, we need
        # to make sure we disable it. However, if a user has already enabled it
        # on upgrade, we need to make sure we don't flip it off by mistake.
	    ${OMV_MKCONF_SCRIPTS_DIR}/pam.d/12-kerberos

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
