#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @author	 Ilya Kogan <ikogan@flarecode.com>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
# @copyright Copyright (c) 2015		 Ilya Kogan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

[ "$(omv_config_get "//services/ssh/enable")" = "0" -o \
  "$(omv_config_get "//services/kerberos/integrations/ssh)" = "0" -o \
  "$(omv_config_get "//services/kerberos/enable")" = "0" ] && exit 0

. ${OMV_MKCONF_SCRIPTS_DIR}/ssh

xmlstarlet sel -t -m "//services/kerberos" \
	-o "KerberosAuthentication yes" -n \
	-o "GSSAPIAuthentication yes" -n \
	${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_SSHD_CONFIG}